backend:
  name: github
  repo: Danykas30/vyciotv  # Replace with your actual GitHub repo
  branch: main

media_folder: "assets/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
